// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTiu6nYK-hJaXQQf3AzLDpgglg2p-Uxnk',
    appId: '1:140420598922:web:c3e33fb76121f85d197173',
    messagingSenderId: '140420598922',
    projectId: 'weather-e21bb',
    authDomain: 'weather-e21bb.firebaseapp.com',
    storageBucket: 'weather-e21bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppEjPISNMSmVSzPlsSIYgSLug-7gkCdY',
    appId: '1:140420598922:android:ffdee49fe2d1c237197173',
    messagingSenderId: '140420598922',
    projectId: 'weather-e21bb',
    storageBucket: 'weather-e21bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaaHsC_eB5LUigQEeXd5QAiAG3FelLDY',
    appId: '1:140420598922:ios:7f6ceefbed6fc045197173',
    messagingSenderId: '140420598922',
    projectId: 'weather-e21bb',
    storageBucket: 'weather-e21bb.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaaHsC_eB5LUigQEeXd5QAiAG3FelLDY',
    appId: '1:140420598922:ios:7f6ceefbed6fc045197173',
    messagingSenderId: '140420598922',
    projectId: 'weather-e21bb',
    storageBucket: 'weather-e21bb.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTiu6nYK-hJaXQQf3AzLDpgglg2p-Uxnk',
    appId: '1:140420598922:web:7f3864c2f01101c6197173',
    messagingSenderId: '140420598922',
    projectId: 'weather-e21bb',
    authDomain: 'weather-e21bb.firebaseapp.com',
    storageBucket: 'weather-e21bb.firebasestorage.app',
  );
}
